services:
- type: web
  name: nextjs-static
  env: static
  buildCommand: yarn; yarn build; yarn next export
  staticPublishPath: out
  pullRequestPreviewsEnabled: true
  envVars:
  - key: NODE_ENV
    value: production